### ISSUE TITLE
"i is not a constructor"

### ISSUE THREAD

**Issue by derhuebiii** [NayanKhedkar/adapt-topNavigator#1]
When using the plugin and going to the project settings I get this error. Any ideas?

![image](https://user-images.githubusercontent.com/22290552/37419607-1eacb9dc-27b5-11e8-86b6-aeed2e0dfff4.png)

**Comment by NayanKhedkar** [comment]
Thanks ! @derhuebiii i fixed the error please give a try.

**Comment by derhuebiii** [comment]
Yes, it works. For anyone who has it already installed - you also need to update the version in bower.json or the framework won't let you overwrite the extension.

Anyway, it doesn't pick the "image" when I upload one. Also I don't think the src object (in properties.schema) should be required, as it will use the css arrow if no src is given, correct?
