### ISSUE TITLE
Not appearing in IE11

### ISSUE THREAD

**Issue by barryjenkin** [NayanKhedkar/adapt-topNavigator#2]
Hi there. 
Love this extension but can't get it to work in Explorer 11. 
Class .top-navigator-arrow stays in .visibility-hidden mode from the time it scrolls down at top of page. Any tips would be greatly appreciated. :)

**Comment by NayanKhedkar** [comment]
Thanks! @barryjenkin any chance you could test this out?
https://github.com/NayanKhedkar/adapt-topNavigator/tree/issue/2

**Comment by barryjenkin** [comment]
Yep - working great now. Thanks for the quick response! :)
